# `docker-compose.local.yml` defines services that must be run locally
# to support a fully self-contained local development environment.

services:
  ui:
    build:
      target: development
    command: npm run start:dev
    depends_on:
      - redis
      - api
      - wiremock
    volumes:
      - ../:/app:cached
      - node_modules:/app/node_modules
    environment:
      TOKEN_VERIFICATION_ENABLED: false
      TOKEN_VERIFICATION_API_URL: http://localhost:9090/verification
      HMPPS_AUTH_URL: http://auth:8080/auth
      HMPPS_AUTH_EXTERNAL_URL: http://localhost:9090/auth
      HMPPS_ARNS_HANDOVER_URL: ${HMPPS_ARNS_HANDOVER_URL:-http://arns-handover:7070}
      HMPPS_ARNS_HANDOVER_EXTERNAL_URL: ${HMPPS_ARNS_HANDOVER_EXTERNAL_URL:-http://localhost:7070}
      HMPPS_ARNS_HANDOVER_CLIENT_ID: arns-assessment-platform
      HMPPS_ARNS_HANDOVER_CLIENT_SECRET: aap-secret
      AAP_API_URL: http://api:8080
      DELIUS_API_URL: http://wiremock:8080
      COORDINATOR_API_URL: http://arns-coordinator:8080
      NODE_ENV: 'development'
      ENVIRONMENT_NAME: dev
      NODE_CLUSTER_ENABLED: false

volumes:
  node_modules:
    external: true # volume gets setup by `make install-node-modules`
    name: ${COMPOSE_PROJECT_NAME}_node_modules
