---
# Per environment values which override defaults in hmpps-arns-assessment-platform-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: arns-assessment-platform-dev.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://arns-assessment-platform-ui-dev.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    HMPPS_ARNS_HANDOVER_URL: "https://arns-handover-service-dev.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    AAP_API_URL: "https://arns-assessment-platform-api-dev.hmpps.service.justice.gov.uk"
    ENVIRONMENT_NAME: DEV
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-arns-non-prod
