---
# Per environment values which override defaults in hmpps-arns-assessment-platform-ui/values.yaml

generic-service:
  ingress:
    host: arns-assessment-platform-ui.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://arns-assessment-platform-ui.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in.hmpps.service.justice.gov.uk/auth"
    HMPPS_ARNS_HANDOVER_URL: "https://arns-handover-service.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api.prison.service.justice.gov.uk"
    AAP_API_URL: "https://arns-assessment-platform-api.hmpps.service.justice.gov.uk"
    AUDIT_ENABLED: "false"

generic-prometheus-alerts:
  alertSeverity: hmpps-arns-prod
