---
# Per environment values which override defaults in hmpps-arns-assessment-platform-ui/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: arns-assessment-platform-test.hmpps.service.justice.gov.uk

  env:
    INGRESS_URL: "https://arns-assessment-platform-test.hmpps.service.justice.gov.uk"
    HMPPS_AUTH_URL: "https://sign-in-dev.hmpps.service.justice.gov.uk/auth"
    HMPPS_ARNS_HANDOVER_URL: "https://arns-handover-service-test.hmpps.service.justice.gov.uk"
    TOKEN_VERIFICATION_API_URL: "https://token-verification-api-dev.prison.service.justice.gov.uk"
    AAP_API_URL: "https://arns-assessment-platform-api-test.hmpps.service.justice.gov.uk"
    COORDINATOR_API_URL: "https://arns-coordinator-api-test.hmpps.service.justice.gov.uk"
    DELIUS_API_URL: "https://sentence-plan-and-delius-dev.hmpps.service.justice.gov.uk"
    ARNS_API_URL: "https://assess-risks-and-needs-test.hmpps.service.justice.gov.uk"
    SAN_URL: "https://strengths-based-needs-assessments-test.hmpps.service.justice.gov.uk"
    OASYS_URL: "https://arns-assessment-platform-test.hmpps.service.justice.gov.uk/training-session-launcher/sessions"
    MPOP_URL: "https://manage-people-on-probation-test.hmpps.service.justice.gov.uk"
    SERVICE_NOW_FORM_URL: "#service-now-link"
    ENVIRONMENT_NAME: TEST
    AUDIT_ENABLED: "false"
    FORM_ENGINE_DEVELOPER_GUIDE_ENABLED: "false"
    TRAINING_SESSION_LAUNCHER_ENABLED: "true"
    SMART_SURVEY_POPUP_CODE: "XF5PNV"

  allowlist:
    capita-dev: 51.104.16.30/31
    captia-further: 172.167.141.40/32
    capita-developers-vms-one: 85.115.52.180/32
    capita-developers-vms-two: 85.115.52.200/29
    capita-developers-vms-three: 85.115.53.180/32
    capita-developers-vms-four: 85.115.53.200/29
    capita-developers-vms-five: 85.115.54.180/32
    capita-developers-vms-six: 85.115.54.200/29
    kpmg-pentest: 195.68.59.74/32

generic-prometheus-alerts:
  alertSeverity: hmpps-arns-non-prod
